export const WORDS = new Map<string, string[]>([
  ["airport", ["travel", "runway", "terminal", "flight"]],
  ["ambulance", ["emergency", "paramedic", "siren", "medical"]],
  ["animal", ["creature", "pet", "wildlife", "beast"]],
  ["apartment", ["building", "rent", "condo", "dwelling"]],
  ["apple", ["fruit", "orchard", "pie", "tree"]],
  ["archaeologist", ["dig", "fossils", "ancient", "excavation"]],
  ["astronaut", ["space", "rocket", "cosmos", "orbit"]],
  ["baby", ["infant", "newborn", "child", "toddler"]],
  ["bakery", ["bread", "cake", "pastry", "shop"]],
  ["balloon", ["party", "float", "inflatable", "helium"]],
  ["bank", ["money", "account", "financial", "vault"]],
  ["barbecue", ["grill", "cookout", "smoke", "BBQ"]],
  ["barn", ["farm", "hay", "stable", "silo"]],
  ["baseball", ["bat", "diamond", "pitch", "glove"]],
  ["beach", ["sand", "ocean", "shore", "wave"]],
  ["bear", ["wildlife", "forest", "cub", "hibernate"]],
  ["bicycle", ["bike", "ride", "wheel", "pedal"]],
  ["bird", ["feather", "wing", "nest", "fly"]],
  ["birthday", ["celebration", "cake", "candles", "gift"]],
  ["blanket", ["cover", "warm", "quilt", "throw"]],
  ["blizzard", ["snow", "storm", "winter", "cold"]],
  ["boat", ["sail", "vessel", "ship", "water"]],
  ["book", ["read", "page", "chapter", "novel"]],
  ["bridge", ["crossing", "river", "span", "architecture"]],
  ["broccoli", ["vegetable", "green", "healthy", "food"]],
  ["bus", ["transport", "route", "passenger", "commute"]],
  ["butterfly", ["wings", "insect", "caterpillar", "flutter"]],
  ["cactus", ["desert", "plant", "spiky", "succulent"]],
  ["cafeteria", ["lunch", "dining", "tray", "food court"]],
  ["cake", ["bake", "frosting", "layer", "dessert"]],
  ["camera", ["photo", "lens", "snapshot", "picture"]],
  ["campfire", ["tent", "marshmallow", "outdoors", "glow"]],
  ["candle", ["flame", "wax", "light", "wick"]],
  ["candy", ["sweet", "treat", "sugar", "chocolate"]],
  ["car", ["drive", "vehicle", "automobile", "road"]],
  ["castle", ["king", "fortress", "moat", "palace"]],
  ["cave", ["grotto", "dark", "underground", "dungeon"]],
  ["chocolate", ["cocoa", "sweet", "candy", "dessert"]],
  ["church", ["worship", "steeple", "congregation", "sacred"]],
  ["circus", ["clown", "tent", "acrobats", "ring"]],
  ["clown", ["circus", "funny", "face paint", "entertainer"]],
  ["coffee", ["brew", "bean", "café", "espresso"]],
  ["comet", ["tail", "space", "meteor", "cosmic"]],
  ["cookie", ["bake", "dough", "sweet", "treat"]],
  ["cow", ["moo", "dairy", "cattle", "farm"]],
  ["crayon", ["color", "draw", "wax", "art"]],
  ["crowd", ["people", "gather", "audience", "mob"]],
  ["dinosaur", ["fossil", "extinct", "prehistoric", "T-Rex"]],
  ["doctor", ["physician", "hospital", "stethoscope", "healer"]],
  ["dog", ["bark", "puppy", "canine", "pet"]],
  ["dragon", ["mythical", "scales", "fire-breathing", "legend"]],
  ["dream", ["sleep", "fantasy", "imagination", "nightmare"]],
  ["drum", ["beat", "percussion", "stick", "rhythm"]],
  ["elephant", ["trunk", "tusks", "large", "gray"]],
  ["emergency", ["urgent", "911", "crisis", "alert"]],
  ["engine", ["motor", "mechanical", "power", "machine"]],
  ["factory", ["manufacture", "production", "plant", "assembly"]],
  ["fairy", ["magic", "winged", "fantasy", "pixie"]],
  ["farm", ["agriculture", "crops", "harvest", "barn"]],
  ["firefighter", ["extinguish", "flames", "hose", "brave"]],
  ["fireworks", ["display", "pyrotechnics", "spark", "rocket"]],
  ["fishing", ["hook", "rod", "catch", "lake"]],
  ["forest", ["woods", "trees", "foliage", "nature"]],
  ["fortune", ["luck", "wealth", "destiny", "fate"]],
  ["frog", ["hop", "amphibian", "pond", "jump"]],
  ["garage", ["parking", "workshop", "car", "storage"]],
  ["garden", ["flower", "plant", "grow", "yard"]],
  ["giraffe", ["neck", "tall", "spots", "savanna"]],
  ["glasses", ["eyewear", "frames", "vision", "spectacles"]],
  ["golf", ["club", "course", "putt", "tee"]],
  ["graveyard", ["cemetery", "tomb", "grave", "memorial"]],
  ["guitar", ["strings", "strum", "musical instrument", "fret"]],
  ["hairdresser", ["salon", "cut", "style", "barber"]],
  ["hamster", ["cage", "rodent", "pet", "wheel"]],
  ["hat", ["headwear", "cap", "brim", "wear"]],
  ["helicopter", ["rotor", "chopper", "fly", "propeller"]],
  ["highway", ["road", "expressway", "interstate", "drive"]],
  ["hippopotamus", ["river", "large", "hippo", "semi-aquatic"]],
  ["hospital", ["medical", "patient", "clinic", "health"]],
  ["hotel", ["stay", "room", "lodge", "accommodation"]],
  ["house", ["home", "dwelling", "residence", "building"]],
  ["ice cream", ["cold", "scoop", "cone", "frozen"]],
  ["igloo", ["snow", "arctic", "ice", "dome"]],
  ["island", ["land", "tropical", "peninsula", "shore"]],
  ["jail", ["prison", "cell", "behind bars", "locked"]],
  ["jellyfish", ["sting", "tentacles", "ocean", "translucent"]],
  ["jungle", ["rainforest", "tropical", "wild", "foliage"]],
  ["kangaroo", ["hop", "marsupial", "pouch", "Australia"]],
  ["ketchup", ["tomato", "sauce", "condiment", "bottle"]],
  ["keyboard", ["keys", "type", "computer", "input"]],
  ["king", ["royal", "crown", "monarch", "ruler"]],
  ["kitchen", ["cook", "stove", "counter", "appliance"]],
  ["kite", ["fly", "wind", "string", "soar"]],
  ["knight", ["armor", "sword", "medieval", "castle"]],
  ["ladder", ["climb", "rungs", "step", "rungs"]],
  ["lake", ["water", "pond", "shore", "calm"]],
  ["lamp", ["light", "bulb", "shade", "illuminate"]],
  ["library", ["books", "shelves", "read", "quiet"]],
  ["lion", ["mane", "roar", "king of beasts", "pride"]],
  ["lizard", ["reptile", "scale", "gecko", "cold-blooded"]],
  ["luggage", ["baggage", "suitcase", "travel", "packed"]],
  ["magnet", ["attract", "metal", "north", "pull"]],
  ["mailman", ["postal", "deliver", "letter", "carrier"]],
  ["mammoth", ["woolly", "extinct", "prehistoric", "tusks"]],
  ["mango", ["tropical", "fruit", "ripe", "smoothie"]],
  ["market", ["shop", "store", "bazaar", "grocery"]],
  ["medal", ["award", "ribbon", "prize", "honor"]],
  ["mermaid", ["mythical", "tail", "ocean", "siren"]],
  ["mountain", ["peak", "summit", "climb", "elevation"]],
  ["mouse", ["rodent", "click", "pet", "small"]],
  ["museum", ["exhibit", "artifact", "gallery", "history"]],
  ["musician", ["performer", "instrument", "artist", "band"]],
  ["nail", ["hammer", "fastener", "fingernail", "screw"]],
  ["nest", ["bird", "eggs", "feathers", "habitat"]],
  ["newspaper", ["headline", "journal", "print", "news"]],
  ["ninja", ["stealth", "martial arts", "shuriken", "assassin"]],
  ["notebook", ["journal", "pad", "write", "notes"]],
  ["ocean", ["sea", "waves", "marine", "deep"]],
  ["olive", ["fruit", "Mediterranean", "oil", "green"]],
  ["oxygen", ["breathe", "air", "element", "gas"]],
  ["palace", ["royal", "grand", "castle", "throne"]],
  ["panda", ["bear", "bamboo", "black and white", "endangered"]],
  ["paper", ["sheet", "write", "document", "stationery"]],
  ["parachute", ["jump", "skydive", "canopy", "air"]],
  ["parrot", ["bird", "mimic", "tropical", "plumage"]],
  ["pencil", ["write", "graphite", "eraser", "draw"]],
  ["penguin", ["tuxedo", "waddle", "antarctic", "flightless"]],
  ["pharaoh", ["egyptian", "pyramid", "araoh", "araoh"]],
  ["pharmacy", ["drugstore", "prescription", "chemist", "medicine"]],
  ["pirate", ["plunder", "treasure", "ship", "eye patch"]],
  ["pizza", ["slice", "toppings", "cheese", "dough"]],
  ["plant", ["grow", "leaf", "vegetation", "green"]],
  ["platypus", ["bill", "venomous", "duck-billed", "unusual"]],
  ["polar bear", ["arctic", "white", "predator", "ice"]],
  ["police", ["officer", "law", "patrol", "enforce"]],
  ["popsicle", ["frozen", "treat", "stick", "ice"]],
  ["prison", ["jail", "inmate", "behind bars", "locked"]],
  ["pumpkin", ["gourd", "orange", "Halloween", "pie"]],
  ["queen", ["royal", "crown", "monarch", "sovereign"]],
  ["rabbit", ["bunny", "hare", "carrot", "hop"]],
  ["rainbow", ["colors", "arc", "prism", "spectrum"]],
  ["record", ["vinyl", "album", "music", "disk"]],
  ["restaurant", ["dine", "menu", "eatery", "cuisine"]],
  ["robot", ["mechanical", "automaton", "android", "cyborg"]],
  ["rocket", ["space", "launch", "fuel", "blast"]],
  ["roller coaster", ["ride", "loop", "amusement park", "thrill"]],
  ["royal", ["king", "queen", "noble", "crown"]],
  ["ruler", ["measure", "king", "monarch", "straight edge"]],
  ["sailboat", ["sail", "wind", "mast", "sea"]],
  ["sandwich", ["bread", "filling", "lunch", "deli"]],
  ["school", ["student", "education", "classroom", "learn"]],
  ["scissors", ["cut", "snip", "shears", "blade"]],
  ["scorpion", ["sting", "tail", "pincer", "arachnid"]],
  ["seafood", ["fish", "shrimp", "crab", "ocean"]],
  ["shark", ["fin", "predator", "ocean", "teeth"]],
  ["sheep", ["wool", "baa", "flock", "lamb"]],
  ["ship", ["sail", "vessel", "ocean", "captain"]],
  ["shoe", ["footwear", "sneaker", "boot", "sole"]],
  ["shopping", ["store", "buy", "mall", "retail"]],
  ["skateboard", ["ride", "deck", "wheels", "trick"]],
  ["skyscraper", ["tall", "building", "skyline", "tower"]],
  ["sleep", ["rest", "dream", "slumber", "nap"]],
  ["snail", ["shell", "slow", "garden", "slug"]],
  ["snake", ["hiss", "slither", "reptile", "venom"]],
  ["snowflake", ["snow", "crystal", "unique", "winter"]],
  ["soccer", ["football", "goal", "kick", "pitch"]],
  ["spider", ["web", "insect", "arachnid", "creepy"]],
  ["sponge", ["absorb", "clean", "porous", "sea"]],
  ["stadium", ["arena", "sport", "spectator", "venue"]],
  ["statue", ["sculpture", "monument", "figure", "bronze"]],
  ["storm", ["thunder", "lightning", "rain", "tempest"]],
  ["subway", ["underground", "metro", "tunnel", "transit"]],
  ["suitcase", ["luggage", "travel", "pack", "bag"]],
  ["sun", ["star", "heat", "daylight", "bright"]],
  ["supermarket", ["grocery", "store", "aisles", "shop"]],
  ["surprise", ["unexpected", "shock", "astonish", "reveal"]],
  ["teacher", ["educator", "instructor", "mentor", "classroom"]],
  ["telescope", ["astronomy", "magnify", "observe", "lens"]],
  ["temple", ["shrine", "worship", "sacred", "ancient"]],
  ["thermometer", ["temperature", "mercury", "fever", "gauge"]],
  ["tiger", ["stripes", "big cat", "predator", "feline"]],
  ["toaster", ["toast", "bread", "appliance", "browning"]],
  ["toilet", ["flush", "bathroom", "porcelain", "plumbing"]],
  ["tomato", ["red", "fruit", "sauce", "vine"]],
  ["treasure", ["gold", "jewels", "bounty", "chest"]],
  ["tree", ["wood", "branch", "leaf", "root"]],
  ["truck", ["vehicle", "haul", "cargo", "pickup"]],
  ["trumpet", ["brass", "blow", "jazz", "horns"]],
  ["tunnel", ["underground", "passage", "bore", "underpass"]],
  ["turtle", ["shell", "reptile", "slow", "pond"]],
  ["umbrella", ["rain", "canopy", "protection", "parasol"]],
  ["unicorn", ["mythical", "horn", "horse", "fantasy"]],
  ["vacuum", ["suction", "clean", "dust", "appliance"]],
  ["valley", ["canyon", "lowland", "gorge", "depression"]],
  ["volcano", ["eruption", "lava", "crater", "ash"]],
  ["waiter", ["serve", "restaurant", "menu", "dining"]],
  ["waterfall", ["cascade", "falls", "plunge", "stream"]],
  ["whale", ["ocean", "mammal", "blowhole", "marine"]],
  ["wheel", ["roll", "tire", "circular", "turn"]],
  ["window", ["glass", "view", "pane", "sill"]],
  ["witch", ["magic", "cauldron", "spell", "wizard"]],
  ["wizard", ["magic", "spell", "hat", "fantasy"]],
  ["yacht", ["boat", "sail", "luxury", "cruise"]],
  ["yogurt", ["dairy", "culture", "smooth", "parfait"]],
  ["zebra", ["stripes", "equine", "safari", "african"]],
]);

export function pickRandomWord(): [string, string[]] {
  const keys = [...WORDS.keys()];
  const key = keys[Math.floor(Math.random() * keys.length)]!;
  return [key, WORDS.get(key)!];
}
